#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';

const ORIGIN = new Date('2021-06-19');
const API_BASE = 'https://www.nytimes.com/svc/wordle/v2';

const root = process.cwd();
const dataDir = path.join(root, 'src', 'data');
const answersByDateTxtPath = path.join(dataDir, 'answers_by_date_wordlist.txt');
const answersByDateTsPath = path.join(root, 'src', 'lib', 'wordle', 'answersByDate.ts');

function formatDate(d) {
  const yyyy = d.getUTCFullYear();
  const mm = String(d.getUTCMonth() + 1).padStart(2, '0');
  const dd = String(d.getUTCDate()).padStart(2, '0');
  return `${yyyy}-${mm}-${dd}`;
}

function yesterdayUtc() {
  const now = new Date();
  const y = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate()));
  y.setUTCDate(y.getUTCDate() - 1);
  return y;
}

async function fetchAnswer(dateStr) {
  const url = `${API_BASE}/${dateStr}.json`;
  const res = await fetch(url);
  if (!res.ok) throw new Error(`HTTP ${res.status} for ${dateStr}`);
  const json = await res.json();
  if (typeof json.solution !== 'string' || json.solution.length !== 5) {
    throw new Error(`Invalid solution for ${dateStr}: ${JSON.stringify(json.solution)}`);
  }
  return json.solution.toLowerCase();
}

async function main() {
  const endDate = yesterdayUtc();
  const dates = [];
  const d = new Date(ORIGIN);
  while (d <= endDate) {
    dates.push(formatDate(d));
    d.setUTCDate(d.getUTCDate() + 1);
  }

  console.log(`Fetching ${dates.length} answers (${dates[0]} to ${dates[dates.length - 1]})...`);

  // Read existing answers to avoid re-fetching unchanged ones.
  let existing = [];
  try {
    const raw = fs.readFileSync(answersByDateTxtPath, 'utf8');
    existing = raw.split(/[\r\n,]+/).map(w => w.trim().toLowerCase()).filter(w => /^[a-z]{5}$/.test(w));
  } catch { /* first run */ }

  const answers = [];
  let fetched = 0;
  for (let i = 0; i < dates.length; i++) {
    if (i < existing.length) {
      // Trust existing entry — only re-fetch if we need more entries.
      answers.push(existing[i]);
      continue;
    }
    const word = await fetchAnswer(dates[i]);
    answers.push(word);
    fetched++;
    // Rate-limit: small delay between API calls.
    if (fetched % 50 === 0) {
      console.log(`  ...fetched ${fetched} new answers (up to ${dates[i]})`);
      await new Promise(r => setTimeout(r, 200));
    }
  }

  console.log(`Done. ${answers.length} total answers, ${fetched} newly fetched.`);

  // Write answers_by_date_wordlist.txt (comma-separated, single line).
  fs.writeFileSync(answersByDateTxtPath, answers.join(',') + '\n', 'utf8');

  // Write answersByDate.ts.
  const tsContent = `// Auto-generated by scripts/fetch-answers.mjs — do not edit manually\n// originDate: 2021-06-19 (Wordle #1 = cigar)\nexport const ANSWERS_BY_DATE: string[] = ${JSON.stringify(answers)};\n`;
  fs.writeFileSync(answersByDateTsPath, tsContent, 'utf8');

  console.log(`Wrote ${answersByDateTxtPath}`);
  console.log(`Wrote ${answersByDateTsPath}`);
}

main().catch(err => {
  console.error(err);
  process.exit(1);
});
